# Files from: zhenkun.y@gmail.com
language: c
compiler:
  - gcc
  - clang
script: make && make test

# need to install the Boost libraries to the sandbox
before_script:
  - sudo apt-get install expect
notifications:
  email:
    recipients: dany4madden@gmail.com
    on_success: always
    on_failure: always
